Ej.1: Diseñar una función que devuelva el máximo entre tres números recibidos como parámetros.

In [4]:
def buscar_maximo(num1,num2,num3):
  maximo = num1
  if (num2 > maximo):
    maximo = num2
  if (num3 > maximo):
    maximo = num3
  return maximo

numero1 = float(input('Ingrese el primer numero: '))
numero2 = float(input('Ingrese el segundo numero: '))
numero3 = float(input('Ingrese el tercer numero: '))

max = buscar_maximo(numero1, numero2, numero3)
print(f'El maximo es: {max}')

Ingrese el primer numero: 2
Ingrese el segundo numero: 7
Ingrese el tercer numero: 4
El maximo es: 7.0

Ej.2: Programar una función que reciba una lista de números como parámetro y calcule la suma de los números.

In [7]:
def sumar_numeros(lista_numeros):
  suma = 0 #Variable "acumulador"
  for numero in lista_numeros:
    suma = suma + numero
  return suma

# Flujo principal
numeros = [1,2,3,5,10]
suma = sumar_numeros(numeros)
print(f'La suma es {suma}')

La suma es 21

In [8]:
# Otra implementacion
def sumar_lista (lista):
  resultado = sum(lista)
  return resultado

numeros = [1,2,3,5,10]
suma = sumar_lista(numeros)
print (suma)

21

Ej.3: Programar una función que reciba una lista con al menos 5 números como parámetro y retorne los 3 menores.

In [26]:
def ordenar(lista):
  menores = lista
  menores.sort()
  #menores = lista[0:3]
  num1 = menores[0]
  num2 = menores[1]
  num3 = menores[2]
  return num1,num2,num3

numeros = [10,2,5,3,1]
num1, num2, num3 = ordenar(numeros)
print(num1)
print(num2)
print(num3)

1
2
3

Ej.4: Dadas las siguientes listas apareadas "nombres" y "edades", se pide ordenar por edad de menor a mayor (recuerde que, entre arreglos relacionados, las posiciones indican la relación que hay entre los datos de estos, así en el ejemplo, el nombre “Juan” se corresponde con la edad 28, “Pablo” con la edad 22, etc.)

In [30]:
nombres = ['Juan', 'Pablo', 'Damián', 'Manuel', 'Nahuel', 'Lucas']
edades = [ 28, 22, 12, 18, 25, 43 ]

zipeadas = zip(edades, nombres)
ordenada = sorted(zipeadas)
print(ordenada)

[(12, 'Damián'), (18, 'Manuel'), (22, 'Pablo'), (25, 'Nahuel'), (28, 'Juan'), (43, 'Lucas')]